name: Check Expiring Foods

on:
  schedule:
    - cron: '0 9 */2 * *'
  workflow_dispatch:

jobs:
  check-expiry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Call expiry check API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-cron-secret: ${{ secrets.CRON_JOB_SECRET }}" \
            ${{ secrets.NEXT_PUBLIC_APP_URL }}/api/cron/check-expiry
        env:
          CRON_JOB_SECRET: ${{ secrets.CRON_JOB_SECRET }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
